syntax on
set mouse=r
set number
set encoding=utf-8
set noshowmode
set noruler

" Automatically change cwd to file's one
set autochdir


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Filetepe Settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype plugin indent on
setlocal shiftwidth=4 softtabstop=4 expandtab

autocmd FileType python setlocal shiftwidth=4 softtabstop=4 expandtab
autocmd FileType yaml,json setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType javascript setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType html,ruby setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType sh setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType make set noexpandtab


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom colors
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
hi User1 ctermbg=black ctermfg=white guibg=black guifg=white
hi User2 ctermbg=black ctermfg=lightgreen guibg=black guifg=lightgreen
hi User3 ctermbg=lightgreen ctermfg=black guibg=lightgreen guifg=black
hi User4 ctermbg=black ctermfg=darkgrey guibg=black guifg=darkgrey
hi User5 ctermbg=darkgrey ctermfg=black guibg=darkgrey guifg=black
hi User6 ctermbg=red ctermfg=black guibg=red guifg=black
hi User7 ctermbg=black ctermfg=red guibg=black guifg=red
hi User8 ctermbg=black ctermfg=cyan guibg=black  ctermfg=cyan
hi User9 ctermbg=cyan ctermfg=black guibg=cyan ctermfg=black


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Setup staus bar
" 
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set laststatus=2
" set statusline=
set statusline=%1*\ 
set statusline+=%{%StatuslineMode()%}
set statusline+=%1*
" Middle Section
set statusline+=%=
set statusline+=%7*%M%1*\ \"%f\"
" Right section
set statusline+=%=
set statusline+=[buff\ %n]\ %LL\ 
set statusline+=%4*%5*curs\ %l:%c%4*
set statusline+=%1*\ 

function! StatuslineMode()
  let l:mode=mode()
  if l:mode==#"n"
    return "%2*%3*NORMAL%2*"
  elseif l:mode==?"v"
    return "%#Statement#%#Search#VISUAL%#Statement#"
  elseif l:mode==#"i"
    return "%4*%5*INSERT%4*"
  elseif l:mode==#"R"
    return "%8*%9*REPLACE%8*"
  elseif l:mode==?"s"
    return "SELECT"
  elseif l:mode==#"t"
    return "%2*%3*TERMINAL%2*"
  elseif l:mode==#"c"
    return "%2*%3*COMMAND%2*"
  elseif l:mode==#"!"
    return "%2*%3*SHELL%2*"
  endif
endfunction


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key remapping
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Disable <F1>
nmap <F1> :echo<CR>


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Colors settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enables cursor line position tracking:
set cursorline
hi CursorLine None
hi CursorLineNR None ctermfg=White
hi LineNr ctermfg=DarkGray
